#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/../vendor/autoload.php';

use Webrium\App;
use Symfony\Component\Console\Application;

use Webrium\Console\GenerateModel;

// echo 'end';
App::rootPath(__DIR__);

$application = new Application();

// // ... register commands
$application->add(new GenerateModel());
// $application->add(new GenerateController());
// $application->add(new DownloadUIBootstrap());

$application->run();